FROM repo.docker.com/dotnet/aspnet:6.0-curl AS base
ENV TZ=Asia/Tehran 
WORKDIR /app

FROM repo.docker.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . .
WORKDIR "/src/MessageDispatcher"
RUN dotnet restore "MessageDispatcher.csproj"
RUN dotnet build "MessageDispatcher.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MessageDispatcher.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MessageDispatcher.dll"]